import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Safety net: ensure wasm assets are copied and embedded before bundling.
// package.json scripts call copy-wasm + embed-wasm first, but esbuild.config.mjs
// may be invoked directly (e.g. by Obsidian's hot-reload).
function ensureWasmReady() {
	if (!fs.existsSync(path.join(process.cwd(), 'wasm', 'web-tree-sitter.wasm'))) {
		try { execSync('node scripts/copy-wasm.mjs', { encoding: 'utf-8', stdio: 'pipe' }); } catch {}
	}
	if (!fs.existsSync(path.join(process.cwd(), 'src', 'indexer', 'wasm-embedded.ts'))) {
		try { execSync('node scripts/embed-wasm.mjs', { encoding: 'utf-8', stdio: 'pipe' }); } catch {}
	}
}

ensureWasmReady();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
		format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

await context.rebuild();

if (prod) {
	process.exit(0);
} else {
	await context.watch();
}
