/**
 * Build-time script: embeds the tree-sitter core runtime + the 4 grammar wasm
 * files that are actually used at runtime (TS, TSX, JS, Python) as GZIP +
 * base64 constants in a generated TypeScript module.
 *
 * This makes the plugin self-contained: a fresh install from a GitHub release
 * (main.js + manifest.json + styles.css) has everything it needs to run
 * tree-sitter parsing without a separate wasm/ directory.
 *
 * **Why gzip:** the raw wasm files total ~3.9 MB. Embedded as plain base64
 * that becomes ~5.3 MB of text in main.js, pushing the bundle past Obsidian's
 * 5 MB sync limit for Obsidian Sync Standard plans. Gzipping first shrinks
 * the payload to ~0.5 MB (~88% smaller); the runtime inflates it with the
 * standard DecompressionStream API (available in every Electron/Chromium
 * Obsidian ships). See gunzipEmbedded() in src/indexer/tree-sitter.ts.
 *
 * The generated module is imported by tree-sitter.ts and used as a fallback
 * when the wasm files are not found on disk.
 *
 * Run automatically by esbuild.config.mjs before each build.
 */
import fs from 'node:fs';
import path from 'node:path';
import { gzipSync } from 'node:zlib';

const WASM_DIR = path.join(process.cwd(), 'wasm');
const GRAMMAR_DIR = path.join(WASM_DIR, 'grammars');
const OUTPUT = path.join(process.cwd(), 'src', 'indexer', 'wasm-embedded.ts');

// Only the grammars for languages with hasSymbolExtraction: true.
// See src/indexer/profiles/registry.ts — these are the only languages that
// ever call parseSource() → loadLanguage().
const NEEDED = [
	{ file: 'web-tree-sitter.wasm', varName: 'CORE_WASM', fromGrammars: false },
	{ file: 'tree-sitter-typescript.wasm', varName: 'TYPESCRIPT_WASM', fromGrammars: true },
	{ file: 'tree-sitter-tsx.wasm', varName: 'TSX_WASM', fromGrammars: true },
	{ file: 'tree-sitter-javascript.wasm', varName: 'JAVASCRIPT_WASM', fromGrammars: true },
	{ file: 'tree-sitter-python.wasm', varName: 'PYTHON_WASM', fromGrammars: true },
];

function embedFile(filePath, varName) {
	const raw = fs.readFileSync(filePath);
	const gz = gzipSync(raw, { level: 9 });
	const b64 = gz.toString('base64');
	return `export const ${varName} = "${b64}";`;
}

const lines = [
	'/**',
	' * AUTO-GENERATED by scripts/embed-wasm.mjs — DO NOT EDIT.',
	' *',
	' * Contains the tree-sitter core runtime + 4 grammar wasm files as GZIP',
	' * bytes encoded as base64. Inflate with DecompressionStream("gzip")',
	' * before use — see gunzipEmbedded() in src/indexer/tree-sitter.ts. Used',
	' * by tree-sitter.ts as a fallback when wasm/ is not on disk (fresh',
	' * install from a GitHub release that only ships main.js + manifest.json).',
	' *',
	' * Gzip keeps the payload at ~0.5 MB instead of ~5.3 MB of plain base64,',
	' * holding main.js under Obsidian\'s 5 MB sync-size limit.',
	' */',
	'',
];

for (const { file, varName, fromGrammars } of NEEDED) {
	const p = path.join(fromGrammars ? GRAMMAR_DIR : WASM_DIR, file);
	if (!fs.existsSync(p)) {
		console.error(`[embed-wasm] missing ${p} — run scripts/copy-wasm.mjs first`);
		process.exit(1);
	}
	lines.push(embedFile(p, varName));
}

const registry = `export const EMBEDDED_WASM_GZIP: Record<string, string> = {
${NEEDED.map(({ file, varName }) => `\t'${file}': ${varName},`).join('\n')}
};

export function getEmbeddedWasmGzip(filename: string): Uint8Array | null {
	const b64 = EMBEDDED_WASM_GZIP[filename];
	if (!b64) return null;
	const bin = atob(b64);
	const bytes = new Uint8Array(bin.length);
	for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
	return bytes;
}
`;

lines.push(registry);

fs.writeFileSync(OUTPUT, lines.join('\n'));

const gzTotal = NEEDED.reduce((acc, { file, fromGrammars }) => {
	const p = path.join(fromGrammars ? GRAMMAR_DIR : WASM_DIR, file);
	return acc + gzipSync(fs.readFileSync(p), { level: 9 }).length;
}, 0);
console.log(
	`[embed-wasm] embedded ${NEEDED.length} wasm files as gzip+base64 (~${Math.round(gzTotal / 1024)} KB gz) → ${path.relative(process.cwd(), OUTPUT)}`,
);
