/**
 * Build-time script: embeds the tree-sitter core runtime + the 4 grammar wasm
 * files that are actually used at runtime (TS, TSX, JS, Python) as base64
 * constants in a generated TypeScript module.
 *
 * This makes the plugin self-contained: a fresh install from a GitHub release
 * (main.js + manifest.json + styles.css) has everything it needs to run
 * tree-sitter parsing without a separate wasm/ directory.
 *
 * The generated module is imported by tree-sitter.ts and used as a fallback
 * when the wasm files are not found on disk.
 *
 * Run automatically by esbuild.config.mjs before each build.
 */
import fs from 'node:fs';
import path from 'node:path';

const WASM_DIR = path.join(process.cwd(), 'wasm');
const GRAMMAR_DIR = path.join(WASM_DIR, 'grammars');
const OUTPUT = path.join(process.cwd(), 'src', 'indexer', 'wasm-embedded.ts');

// Only the grammars for languages with hasSymbolExtraction: true.
// See src/indexer/profiles/registry.ts — these are the only languages that
// ever call parseSource() → loadLanguage().
const NEEDED = [
	{ file: 'web-tree-sitter.wasm', varName: 'CORE_WASM', fromGrammars: false },
	{ file: 'tree-sitter-typescript.wasm', varName: 'TYPESCRIPT_WASM', fromGrammars: true },
	{ file: 'tree-sitter-tsx.wasm', varName: 'TSX_WASM', fromGrammars: true },
	{ file: 'tree-sitter-javascript.wasm', varName: 'JAVASCRIPT_WASM', fromGrammars: true },
	{ file: 'tree-sitter-python.wasm', varName: 'PYTHON_WASM', fromGrammars: true },
];

function embedFile(filePath, varName) {
	const buf = fs.readFileSync(filePath);
	const b64 = buf.toString('base64');
	return `export const ${varName} = "${b64}";`;
}

const lines = [
	'/**',
	' * AUTO-GENERATED by scripts/embed-wasm.mjs — DO NOT EDIT.',
	' *',
	' * Contains the tree-sitter core runtime + 4 grammar wasm files as base64.',
	' * Used by tree-sitter.ts as a fallback when wasm/ is not on disk (fresh',
	' * install from a GitHub release that only ships main.js + manifest.json).',
	' *',
	' * Total embedded: ~5.4 MB base64 (~3.9 MB binary). This is the cost of a',
	' * self-contained single-file install with no external wasm dependencies.',
	' */',
	'',
	'// eslint-disable-next-line @typescript-eslint/no-explicit-any',
	'let _decoded: Record<string, Uint8Array> = {};',
	'',
	'/** Decode a base64 string to a Uint8Array (lazy, cached). */',
	'function decode(b64: string): Uint8Array {',
	'	const bin = atob(b64);',
	'	const len = bin.length;',
	'	const bytes = new Uint8Array(len);',
	'	for (let i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);',
	'	return bytes;',
	'}',
	'',
];

const entries = [];
for (const { file, varName, fromGrammars } of NEEDED) {
	const full = fromGrammars
		? path.join(GRAMMAR_DIR, file)
		: path.join(WASM_DIR, file);
	if (!fs.existsSync(full)) {
		console.warn(`[embed-wasm] WARNING: ${full} not found — skipping. Run npm run build first to copy wasm assets.`);
		continue;
	}
	lines.push(embedFile(full, varName));
	entries.push({ file, varName });
}

lines.push('');
lines.push('/**');
lines.push(' * Map of grammar filename → embedded base64 constant name.');
lines.push(' * Used by tree-sitter.ts to look up embedded bytes by filename.');
lines.push(' */');
lines.push('export const EMBEDDED_WASM: Record<string, string> = {');
for (const { file, varName } of entries) {
	lines.push(`\t'${file}': ${varName},`);
}
lines.push('};');
lines.push('');
lines.push('/**');
lines.push(' * Get embedded wasm bytes for a filename, or null if not embedded.');
lines.push(' * Decodes base64 to Uint8Array on first access and caches the result.');
lines.push(' */');
lines.push('export function getEmbeddedWasm(filename: string): Uint8Array | null {');
lines.push('\tif (_decoded[filename]) return _decoded[filename];');
lines.push('\tconst b64 = EMBEDDED_WASM[filename];');
lines.push('\tif (!b64) return null;');
lines.push('\tconst bytes = decode(b64);');
lines.push('\t_decoded[filename] = bytes;');
lines.push('\treturn bytes;');
lines.push('}');

fs.writeFileSync(OUTPUT, lines.join('\n') + '\n');

const totalBytes = entries.reduce((sum, { varName }) => {
	const match = lines.find((l) => l.startsWith(`export const ${varName} =`));
	if (!match) return sum;
	const b64 = match.match(/"([^"]+)"/)?.[1] ?? '';
	return sum + Math.floor(b64.length * 0.75);
}, 0);

console.log(
	`[embed-wasm] embedded ${entries.length} wasm files (${(totalBytes / 1024 / 1024).toFixed(1)} MB binary) → ${path.relative(process.cwd(), OUTPUT)}`,
);